#!/bin/bash
# List gnome keyboard shortcuts
#
# https://askubuntu.com/questions/725611/how-to-search-through-all-keyboard-shortcuts-that-use-a-certain-key

set -e -u -x  # This is bash.  Be safe.

 gsettings list-recursively | awk '/hotkey/||/keybinding/||/media-key/'
